kserve: use numeric id for nobody
Due to this the following error appears from Kube API:

"""
Error: container has runAsNonRoot and image has non-numeric user (nobody),
cannot verify user is non-root
"""

Bug: T337213
Change-Id: I7cc5f5fa9d67799b0ab8b72ac3e68cb183951485